### PR TITLE
Rename beamline_name to endstation

### LINKED ISSUE #3: Rename `beamline_name` to `endstation`
We use the endstation name when deploying this so `beamline_name` should be renamed.

### PR DESCRIPTION
**Pull request by AbbyGi**
Closes #3.

### CODE REVIEW

**Review by padraic-shafer — APPROVED** [review]
Your update to use `end station` rather than `beamline_name` looks good.

You'll notice that I made some changes to the repo.  Could you please review and merge/edit as needed?

**Comment by padraic-shafer** [comment]
Tests were failing because there were no tests to run.  The simple test I added is not the most informative, but I prefer to seed the test suite rather than disable testing.  Let it be a start!

**Comment by padraic-shafer** [comment]
@AbbyGi Does this look ok?

**Comment by AbbyGi** [comment]
Yep, this looks good. Can't review because I'm the author but I'll merge.

**Pull request merged**
